### PR TITLE
Rewrite the code into C++

### PR DESCRIPTION
**Pull request by Zer0xFF**
I wanted to run the code on OSX/Linux as I don't use Windows much, so I decided to rewrite it in C++ and made it platform independent, it was a straight forward job so I went ahead and refactored the code a little bit.

### CODE REVIEW

**Comment by idc** [comment]
Good work.

There's nothing platform specific about the C# code, so it should run fine under mono/netcore.

I would be interested to accept this into its own branch, but not to replace the code outright in master. However, I think it would be more appropriate to make a new repository for your rewrite.

Thoughts?

**Comment by Zer0xFF** [comment]
I have no objections either way, I thought Ill ping you through a PR so you'd atleast know about this, since this is your work after all.

but ya, someone suggested mono, but I felt it's an over kill for such a small project, plus I've been growing more interested in C++, so I've been C++ all things :p

branch vs repo is really only a difference in terms, I don't mind either.

**Comment by idc** [comment]
A new repository would be less maintenance on my end, and I can point people to your rewrite for those interested in a C++ tool.

**Comment by Zer0xFF** [comment]
now you're leaving me with the creative task of coming up with a name :p

**Comment by Zer0xFF** [comment]
ok I've push it to this repo https://github.com/Thunder07/ps4-pup-unpacker

**Pull request closed without merging**
